### ISSUE TITLE
Exception - 'Grid has no cols (Parameter 'grid')'

### ISSUE THREAD

**Issue by mitchpaulus** [Strukton-Worksphere/haystack-csharp#79]
I am attempting to run the examples shown in the README. I have this as a simple example.

```C#
var user = "user";
var password = "password";

var uri = new Uri("https://ourserver.com/api/");
var auth = new AutodetectAuthenticator(user, password);
var client = new HaystackClient(auth, uri);

await client.OpenAsync();

var result = await client.AboutAsync();
```

This fails on the `AboutAsync()` with the following stack trace:

```
System.ArgumentException
  HResult=0x80070057
  Message=Grid has no cols (Parameter 'grid')
  Source=ProjectHaystack.Client
  StackTrace:
   at ProjectHaystack.io.ZincWriter.WriteGrid(HaystackGrid grid) in haystack-csharp\ProjectHaystack\io\ZincWriter.cs:line 259
   at ProjectHaystack.io.ZincWriter.WriteValue(HaystackValue value) in haystack-csharp\ProjectHaystack\io\ZincWriter.cs:line 93
   at ProjectHaystack.io.ZincWriter.ToZinc(HaystackValue val) in haystack-csharp\ProjectHaystack\io\ZincWriter.cs:line 30
   at ProjectHaystack.Client.HaystackClient.<PostGridAsync>d__35.MoveNext() in haystack-csharp\ProjectHaystack\Client\HaystackClient.cs:line 449
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ProjectHaystack.Client.HaystackClient.<CallAsync>d__34.MoveNext() in haystack-csharp\ProjectHaystack\Client\HaystackClient.cs:line 433

  This exception was originally thrown at this call stack:
    ProjectHaystack.io.ZincWriter.WriteGrid(ProjectHaystack.HaystackGrid) in ZincWriter.cs
    ProjectHaystack.io.ZincWriter.WriteValue(ProjectHaystack.HaystackValue) in ZincWriter.cs
    ProjectHaystack.io.ZincWriter.ToZinc(ProjectHaystack.HaystackValue) in ZincWriter.cs
    ProjectHaystack.Client.HaystackClient.PostGridAsync(string, ProjectHaystack.HaystackGrid) in HaystackClient.cs
    [External Code]
    ProjectHaystack.Client.HaystackClient.CallAsync(string, ProjectHaystack.HaystackGrid) in HaystackClient.cs
```

I don't believe this is an issue with our server instance - the `client.AboutAsync()` method executes fine. It's failing before the post itself as well. The same issue happens with `OpsAsync()` as well.

![image](https://user-images.githubusercontent.com/16965956/122608453-d7fbff00-d041-11eb-9aed-19824c42c54f.png)

**Comment by longjoel** [comment]
I found version 1.8 to be a lot more stable.

**Comment by Breederveld** [comment]
Please also have a look at the latest 2.x version. It does quite drastically change the interfaces (there is also a backcompat package if you need it), but it does make the library much more usable to .NET developers.
